source 'https://rubygems.org'
group :development do
  gem 'guard'
  gem 'guard-livereload'
  gem 'guard-shell'
  gem 'guard-sass'
  gem 'guard-shotgun', :git => 'https://github.com/rchampourlier/guard-shotgun.git'
end
gem 'sass'
gem 'slim'
gem 'sinatra'
gem 'sinatra-partial'
gem 'font-awesome-sass', :github => 'coderanger/font-awesome-sass'
gem 'god'
#gem 'coffee-script' # Bye CoffeeScript. :(
gem 'opal'
gem 'opal-sprockets'
gem 'opal-jquery'
gem 'sinatra-asset-pipeline'
gem 'reel-rack'
gem 'parseconfig'
gem 'uglifier'
gem 'thin'
gem 'andand'
gem 'unicorn'
gem 'sinatra-advanced-routes', :require => 'sinatra/advanced_routes'
